# Generated by Django 5.0.4 on 2024-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(default=dict, verbose_name='Ordered Items Details'),
        ),
    ]
