# Generated by Django 5.0.4 on 2024-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_performance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='avg_response_time',
            field=models.FloatField(default=None, verbose_name='Average Response time in Minutes'),
        ),
    ]
