# Generated by Django 5.0.4 on 2024-04-30 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_purchaseorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='fulfillment_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Order Fulfillment rate of vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='Quality Rating of Order'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Order Fulfillment rate of vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='Quality Rating'),
        ),
    ]
