# Generated by Django 5.0.4 on 2024-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_performance_avg_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity of Items'),
        ),
    ]
