# Generated by Django 5.0.4 on 2024-04-30 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_performance_fulfillment_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='quality_rating_avg',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='Average Quality Rating'),
        ),
    ]
