# Generated by Django 5.0.4 on 2024-05-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_performance_quality_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Date of Performace Record'),
        ),
    ]
