# Generated by Django 5.0.4 on 2024-05-02 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_purchaseorder_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 15, 22, 25, 289076), verbose_name='Order Issue Date to the Vendor'),
        ),
    ]
