# Generated by Django 5.0.4 on 2024-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_purchaseorder_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(default=None, null=True, verbose_name='Average Response time of vendor in hours'),
        ),
    ]
