# Generated by Django 5.0.4 on 2024-05-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_vendor_average_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(verbose_name='Order Acknowledgment Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(verbose_name='Order Issue Date to the Vendor'),
        ),
    ]
