# Generated by Django 5.0.4 on 2024-05-02 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_purchaseorder_acknowledgement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 47, 35, 262980), verbose_name='Order Acknowledgment Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Order Issue Date to the Vendor'),
        ),
    ]
