# Generated by Django 5.0.4 on 2024-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_purchaseorder_acknowledgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Order Acknowledgment Date'),
        ),
    ]
