# Generated by Django 5.0.4 on 2024-05-02 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_purchaseorder_acknowledgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='avg_response_time',
            field=models.FloatField(default=None, verbose_name='Average Response time in Hours'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 59, 46, 952879), verbose_name='Order Acknowledgment Date'),
        ),
    ]
