# Generated by Django 5.0.4 on 2024-05-03 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_purchaseorder_acknowledgement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 11, 54, 16, 394405), null=True, verbose_name='Order Acknowledgment Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 11, 54, 16, 394405), verbose_name='Order Issue Date to the Vendor'),
        ),
    ]
