# Generated by Django 5.0.4 on 2024-05-04 13:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_purchaseorder_acknowledgement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Performace Record'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 4, 19, 15, 50, 803608), null=True, verbose_name='Order Acknowledgment Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 19, 15, 50, 803608), verbose_name='Order Issue Date to the Vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='Quality Rating of Order'),
        ),
    ]
