# Generated by Django 5.0.4 on 2024-05-04 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_performance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 4, 19, 20, 9, 781068), null=True, verbose_name='Order Acknowledgment Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 19, 20, 9, 781068), verbose_name='Order Issue Date to the Vendor'),
        ),
    ]
